server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # PWA — все маршруты отдаём index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API проксируем на backend
    location /api/ {
        proxy_pass http://backend:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 50m;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
}
