ALTER TABLE users
  ADD COLUMN IF NOT EXISTS avatar     TEXT,
  ADD COLUMN IF NOT EXISTS phone      TEXT,
  ADD COLUMN IF NOT EXISTS telegram   TEXT,
  ADD COLUMN IF NOT EXISTS whatsapp   TEXT,
  ADD COLUMN IF NOT EXISTS profession TEXT,
  ADD COLUMN IF NOT EXISTS full_name  TEXT;
