// Строки экрана загрузки урока и превью распознанного (10 языков).
//
// Лежат отдельно от pages/NewLesson.jsx, потому что превью используют ДВА экрана:
// создание урока и дозагрузка фото в готовый урок (LessonList). Пока строки жили
// внутри NewLesson, второй экран не мог их взять, не потянув за собой всю страницу.
export const NSTR = {
  ru: { word: 'Урок', descLabel: 'Описание (необязательно)', descHint: 'Кратко: о чём урок, что тренируем…', book: '📘 Учебник', bookHint: 'Фото страниц учебника', tetrad: '✏️ Тетрадь / доска', tetradHint: 'Свои слова с доски или тетради', selected: (n) => `Выбрано: ${n}`,
    pv: { title: '👀 Проверь, что распознал ИИ', hint: 'Сними галочку с лишнего, дострой то, что пропустил ИИ. Урок создастся только из отмеченного.', words: '📖 Слова', sentences: '💬 Предложения', noWords: 'Слов не распознано.', noSentences: 'Предложений не распознано.', wordPh: 'слово', trPh: 'перевод', addWord: '+ добавить слово', sentPh: 'предложение', addSent: '+ добавить', cancel: 'Отмена', confirm: 'Подтвердить разбор →', fromBook: 'Учебник', fromExtra: 'Тетрадь/доска', cancelConfirm: 'Отменить создание урока? Загруженные фото и распознанное будут удалены.',  grpNew: 'Новые слова', grpNewHint: 'их и добавляем в урок', grpSeen: 'Уже проходили', grpSeenHint: 'упражнения на них уже есть', grpFn: 'Служебные и подписи', grpFnHint: 'артикли, предлоги, заголовки заданий', pickAll: 'все', pickNone: 'снять',} },
  uk: { word: 'Урок', descLabel: 'Опис (необов\'язково)', descHint: 'Коротко: про що урок, що тренуємо…', book: '📘 Підручник', bookHint: 'Фото сторінок підручника', tetrad: '✏️ Зошит / дошка', tetradHint: 'Свої слова з дошки або зошита', selected: (n) => `Обрано: ${n}`,
    pv: { title: '👀 Перевір, що розпізнав ШІ', hint: 'Зніми галочку із зайвого, допиши те, що пропустив ШІ. Урок створиться лише з відміченого.', words: '📖 Слова', sentences: '💬 Речення', noWords: 'Слів не розпізнано.', noSentences: 'Речень не розпізнано.', wordPh: 'слово', trPh: 'переклад', addWord: '+ додати слово', sentPh: 'речення', addSent: '+ додати', cancel: 'Скасувати', confirm: 'Підтвердити розбір →', fromBook: 'Підручник', fromExtra: 'Зошит/дошка', cancelConfirm: 'Скасувати створення уроку? Завантажені фото і розпізнане будуть видалені.',  grpNew: 'Нові слова', grpNewHint: 'їх і додаємо до уроку', grpSeen: 'Вже проходили', grpSeenHint: 'вправи на них уже є', grpFn: 'Службові та заголовки', grpFnHint: 'артиклі, прийменники, назви завдань', pickAll: 'усі', pickNone: 'зняти',} },
  en: { word: 'Lesson', descLabel: 'Description (optional)', descHint: 'Briefly: what the lesson is about…', book: '📘 Textbook', bookHint: 'Photos of textbook pages', tetrad: '✏️ Notebook / board', tetradHint: 'Your own words from the board or notebook', selected: (n) => `Selected: ${n}`,
    pv: { title: '👀 Review what the AI recognized', hint: 'Uncheck anything wrong, add what the AI missed. The lesson will be created only from checked items.', words: '📖 Words', sentences: '💬 Sentences', noWords: 'No words recognized.', noSentences: 'No sentences recognized.', wordPh: 'word', trPh: 'translation', addWord: '+ add word', sentPh: 'sentence', addSent: '+ add', cancel: 'Cancel', confirm: 'Confirm →', fromBook: 'Textbook', fromExtra: 'Notebook/board', cancelConfirm: 'Cancel lesson creation? Uploaded photos and recognized data will be deleted.',  grpNew: 'New words', grpNewHint: 'these go into the lesson', grpSeen: 'Already covered', grpSeenHint: 'exercises already exist', grpFn: 'Function words & headings', grpFnHint: 'articles, prepositions, task titles', pickAll: 'all', pickNone: 'none',} },
  de: { word: 'Lektion', descLabel: 'Beschreibung (optional)', descHint: 'Kurz: worum es geht…', book: '📘 Lehrbuch', bookHint: 'Fotos der Lehrbuchseiten', tetrad: '✏️ Heft / Tafel', tetradHint: 'Eigene Wörter von Tafel oder Heft', selected: (n) => `Ausgewählt: ${n}`,
    pv: { title: '👀 Überprüfe, was die KI erkannt hat', hint: 'Hake Falsches ab, ergänze, was die KI übersehen hat. Die Lektion wird nur aus dem Markierten erstellt.', words: '📖 Wörter', sentences: '💬 Sätze', noWords: 'Keine Wörter erkannt.', noSentences: 'Keine Sätze erkannt.', wordPh: 'Wort', trPh: 'Übersetzung', addWord: '+ Wort hinzufügen', sentPh: 'Satz', addSent: '+ hinzufügen', cancel: 'Abbrechen', confirm: 'Bestätigen →', fromBook: 'Lehrbuch', fromExtra: 'Heft/Tafel', cancelConfirm: 'Lektionserstellung abbrechen? Hochgeladene Fotos und Erkanntes werden gelöscht.',  grpNew: 'Neue Wörter', grpNewHint: 'die kommen in die Lektion', grpSeen: 'Schon gehabt', grpSeenHint: 'Übungen gibt es bereits', grpFn: 'Funktionswörter & Überschriften', grpFnHint: 'Artikel, Präpositionen, Aufgabentitel', pickAll: 'alle', pickNone: 'keine',} },
  bg: { word: 'Урок', descLabel: 'Описание (по избор)', descHint: 'Накратко: за какво е урокът…', book: '📘 Учебник', bookHint: 'Снимки на страници', tetrad: '✏️ Тетрадка / дъска', tetradHint: 'Свои думи от дъската или тетрадката', selected: (n) => `Избрани: ${n}`,
    pv: { title: '👀 Провери какво разпозна ИИ', hint: 'Махни отметката от грешното, добави каквото ИИ е пропуснал. Урокът ще се създаде само от отметнатото.', words: '📖 Думи', sentences: '💬 Изречения', noWords: 'Не са разпознати думи.', noSentences: 'Не са разпознати изречения.', wordPh: 'дума', trPh: 'превод', addWord: '+ добави дума', sentPh: 'изречение', addSent: '+ добави', cancel: 'Отказ', confirm: 'Потвърди →', fromBook: 'Учебник', fromExtra: 'Тетрадка/дъска', cancelConfirm: 'Да се отмени ли създаването на урока? Качените снимки и разпознатото ще бъдат изтрити.',  grpNew: 'Нови думи', grpNewHint: 'те влизат в урока', grpSeen: 'Вече минати', grpSeenHint: 'вече имат упражнения', grpFn: 'Служебни и заглавия', grpFnHint: 'членове, предлози, заглавия', pickAll: 'всички', pickNone: 'нито една',} },
  tr: { word: 'Ders', descLabel: 'Açıklama (isteğe bağlı)', descHint: 'Kısaca: ders ne hakkında…', book: '📘 Ders kitabı', bookHint: 'Ders kitabı sayfaları', tetrad: '✏️ Defter / tahta', tetradHint: 'Tahtadan veya defterden kendi kelimeleriniz', selected: (n) => `Seçildi: ${n}`,
    pv: { title: '👀 Yapay zekânın tanıdığını kontrol et', hint: 'Yanlış olanın işaretini kaldır, yapay zekânın atladığını ekle. Ders yalnızca işaretlenenlerden oluşturulacak.', words: '📖 Kelimeler', sentences: '💬 Cümleler', noWords: 'Kelime tanınmadı.', noSentences: 'Cümle tanınmadı.', wordPh: 'kelime', trPh: 'çeviri', addWord: '+ kelime ekle', sentPh: 'cümle', addSent: '+ ekle', cancel: 'İptal', confirm: 'Onayla →', fromBook: 'Ders kitabı', fromExtra: 'Defter/tahta', cancelConfirm: 'Ders oluşturma iptal edilsin mi? Yüklenen fotoğraflar ve tanınan veriler silinecek.',  grpNew: 'Yeni kelimeler', grpNewHint: 'derse bunlar girer', grpSeen: 'Daha önce geçti', grpSeenHint: 'alıştırmaları zaten var', grpFn: 'İşlev sözcükleri ve başlıklar', grpFnHint: 'artikeller, edatlar, başlıklar', pickAll: 'tümü', pickNone: 'hiçbiri',} },
  ar: { word: 'درس', descLabel: 'وصف (اختياري)', descHint: 'باختصار: عن ماذا الدرس…', book: '📘 الكتاب', bookHint: 'صور صفحات الكتاب', tetrad: '✏️ الدفتر / السبورة', tetradHint: 'كلماتك من السبورة أو الدفتر', selected: (n) => `المحدد: ${n}`,
    pv: { title: '👀 راجع ما تعرف عليه الذكاء الاصطناعي', hint: 'ألغِ تحديد الخاطئ، وأضف ما فاته الذكاء الاصطناعي. سيُنشأ الدرس فقط مما هو محدد.', words: '📖 الكلمات', sentences: '💬 الجمل', noWords: 'لم يتم التعرف على كلمات.', noSentences: 'لم يتم التعرف على جمل.', wordPh: 'كلمة', trPh: 'ترجمة', addWord: '+ إضافة كلمة', sentPh: 'جملة', addSent: '+ إضافة', cancel: 'إلغاء', confirm: 'تأكيد ←', fromBook: 'الكتاب', fromExtra: 'الدفتر/السبورة', cancelConfirm: 'هل تريد إلغاء إنشاء الدرس؟ سيتم حذف الصور المرفوعة والبيانات المتعرف عليها.',  grpNew: 'كلمات جديدة', grpNewHint: 'هذه تدخل الدرس', grpSeen: 'سبق تناولها', grpSeenHint: 'التمارين موجودة بالفعل', grpFn: 'أدوات وعناوين', grpFnHint: 'أدوات التعريف وحروف الجر والعناوين', pickAll: 'الكل', pickNone: 'لا شيء',} },
  es: { word: 'Lección', descLabel: 'Descripción (opcional)', descHint: 'Breve: de qué trata la lección…', book: '📘 Libro', bookHint: 'Fotos de las páginas del libro', tetrad: '✏️ Cuaderno / pizarra', tetradHint: 'Tus palabras de la pizarra o el cuaderno', selected: (n) => `Seleccionadas: ${n}`,
    pv: { title: '👀 Revisa lo que reconoció la IA', hint: 'Desmarca lo incorrecto, añade lo que la IA se saltó. La lección se creará solo con lo marcado.', words: '📖 Palabras', sentences: '💬 Frases', noWords: 'No se reconocieron palabras.', noSentences: 'No se reconocieron frases.', wordPh: 'palabra', trPh: 'traducción', addWord: '+ añadir palabra', sentPh: 'frase', addSent: '+ añadir', cancel: 'Cancelar', confirm: 'Confirmar →', fromBook: 'Libro', fromExtra: 'Cuaderno/pizarra', cancelConfirm: '¿Cancelar la creación de la lección? Las fotos subidas y lo reconocido se eliminarán.',  grpNew: 'Palabras nuevas', grpNewHint: 'estas van a la lección', grpSeen: 'Ya vistas', grpSeenHint: 'ya tienen ejercicios', grpFn: 'Funcionales y títulos', grpFnHint: 'artículos, preposiciones, títulos', pickAll: 'todas', pickNone: 'ninguna',} },
  fr: { word: 'Leçon', descLabel: 'Description (facultatif)', descHint: 'Brièvement : de quoi parle la leçon…', book: '📘 Manuel', bookHint: 'Photos des pages du manuel', tetrad: '✏️ Cahier / tableau', tetradHint: 'Tes propres mots du tableau ou du cahier', selected: (n) => `Sélectionnées : ${n}`,
    pv: { title: '👀 Vérifie ce que l\'IA a reconnu', hint: 'Décoche ce qui est faux, ajoute ce que l\'IA a manqué. La leçon sera créée uniquement avec ce qui est coché.', words: '📖 Mots', sentences: '💬 Phrases', noWords: 'Aucun mot reconnu.', noSentences: 'Aucune phrase reconnue.', wordPh: 'mot', trPh: 'traduction', addWord: '+ ajouter un mot', sentPh: 'phrase', addSent: '+ ajouter', cancel: 'Annuler', confirm: 'Confirmer →', fromBook: 'Manuel', fromExtra: 'Cahier/tableau', cancelConfirm: 'Annuler la création de la leçon ? Les photos téléchargées et les données reconnues seront supprimées.',  grpNew: 'Nouveaux mots', grpNewHint: 'ils vont dans la leçon', grpSeen: 'Déjà vus', grpSeenHint: 'les exercices existent déjà', grpFn: 'Mots outils et titres', grpFnHint: 'articles, prépositions, titres', pickAll: 'tous', pickNone: 'aucun',} },
  sq: { word: 'Mësimi', descLabel: 'Përshkrimi (opsional)', descHint: 'Shkurt: për çfarë është mësimi…', book: '📘 Libri', bookHint: 'Foto të faqeve të librit', tetrad: '✏️ Fletore / dërrasë', tetradHint: 'Fjalët e tua nga dërrasa ose fletorja', selected: (n) => `Zgjedhur: ${n}`,
    pv: { title: '👀 Kontrollo çfarë njohu AI-ja', hint: 'Hiq shenjën nga ajo që s\'është e saktë, shto çfarë AI-ja anashkaloi. Mësimi do të krijohet vetëm nga të shënuarat.', words: '📖 Fjalët', sentences: '💬 Fjalitë', noWords: 'Nuk u njohën fjalë.', noSentences: 'Nuk u njohën fjali.', wordPh: 'fjalë', trPh: 'përkthim', addWord: '+ shto fjalë', sentPh: 'fjali', addSent: '+ shto', cancel: 'Anulo', confirm: 'Konfirmo →', fromBook: 'Libri', fromExtra: 'Fletore/dërrasë', cancelConfirm: 'Të anulohet krijimi i mësimit? Fotot e ngarkuara dhe të dhënat e njohura do të fshihen.',  grpNew: 'Fjalë të reja', grpNewHint: 'këto shkojnë në mësim', grpSeen: 'Të parat më parë', grpSeenHint: 'ushtrimet ekzistojnë', grpFn: 'Fjalë funksionale dhe tituj', grpFnHint: 'nyje, parafjalë, tituj', pickAll: 'të gjitha', pickNone: 'asnjë',} },
}
